name: Gradle Package

on:
  push:
    tags:
      - '*.*.*\+jpa*'

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      id: setup-jdk
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle build
      run: ./gradlew clean build

    - name: Publish to Maven Central
      if: success()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          ./gradlew -PprojectVersion=$GITHUB_REF_NAME publishToSonatype closeSonatypeStagingRepository --info --stacktrace
        else
          echo "Build failed. Skipping deployment to Maven Central."
        fi
      env:
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PWD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
