name: Gradle Package

on:
  push:
    tags:
      - '*.*.*-*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      id: setup-jdk
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Extract release version
      run: |
        export RELEASE_VERSION="${{ github.event.release.tag_name }}"
        echo "Release Version: $RELEASE_VERSION"
      id: extract_release_version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle build
      run: ./gradlew clean build

    - name: Publish to Maven Central
      if: success()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          ./gradlew publish -Pversion=$RELEASE_VERSION --warn --stacktrace --info
        else
          echo "Build failed. Skipping deployment to Maven Central."
        fi
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PWD }}
